In [1]:
import pandas as pd

In [2]:
mturk_abductive_data = pd.read_csv('../mturk/abductive/mturk_data/results/pilot-results.csv').drop(columns=[
    'dataset_name', 'hit_type_id', 'max_assignments', 'post_date', 'posted_hits', 'hit_id', 'requestor_note', 'tasks', 'mturk_assignments', 'example_ids'
])

In [3]:
mturk_abductive_data = pd.concat(
        [mturk_abductive_data, mturk_abductive_data.example_data.map(eval).apply(pd.Series)], axis=1
)
mturk_abductive_data['paraphrases'] = mturk_abductive_data['processed_assignments'].map(eval)
mturk_abductive_data.drop(columns=['processed_assignments', 'example_data'])

,origin_split,example_id,hyp1,hyp2,label,obs1,obs2,split,story_id,paraphrases
0,test,2619,The other team felt bad and gave them another ...,The other team felt great and gave them anothe...,1,One bowling team was so poor that they only co...,Now the team had two balls.,test,1c2fbd02-8750-4341-a5f0-623a78289a79-1,[{'hyp1_paraphrases': ['The other team felt ba...
1,test,456,All of our friends joined us as we got married.,We had our wedding night in the sand.,1,We decided to get married on the beach.,We ended our day with a dip in the cool ocean.,test,69b30472-b8a9-4104-b43c-c070b378a0d0-1,[{'hyp1_paraphrases': ['All of our friends joi...
2,test,102,"Animals began to eat her plants, so Tish obser...",There was a bad storm by Trish's garden.,2,Tish liked gardening in her yard.,Tish's garden started to recover and look brig...,test,530a7f9f-c8b5-4b26-a5f5-0bf05d79d08e-1,[{'hyp1_paraphrases': ['There was a storm by T...
3,test,3037,the pen pal came to the school.,Ari got pen pal luckly meets his long distance...,1,Ari got a pen pal in English class.,Ari was thrilled to meet his long-distance fri...,test,134eab98-2fdb-4994-a342-92c03e2d0e57-1,[{'hyp1_paraphrases': ['Ari's pen pal visited ...
4,test,1126,Molly got into an accident.,She became sticky early on during the trip.,1,Molly was invited on a trip with the church.,She ended up having to rest for the remainder ...,test,9142d780-70fd-4bfd-81c5-4931d30d8f04-1,[{'hyp1_paraphrases': ['Molly was involved in ...
...,...,...,...,...,...,...,...,...,...,...
110,test,271,The chicken got burned.,forgot to stuff it with bread.,2,Marc made chicken for dinner.,"However, it was delicious, so they didn't mind.",test,7045c09d-485b-40a7-a8b7-442d7d4fa9fb-1,[{'hyp1_paraphrases': ['Marc did not put bread...
111,test,864,after a couple of hours.,The waitress wrongly got our order.,1,The waitress came with our orders.,"Thankfully, the waitress prepared another orde...",test,1b920f2c-c704-4ac2-8ef4-d0048a3d5735-1,"[{'hyp1_paraphrases': ['after some time', 'aft..."
112,test,2323,Rita was very excited that a stork was being h...,Rita asked her teacher when the baby would come.,1,Rita's mom said the stork would bring her a ba...,She told her teacher it needed to bring her ba...,test,16df59e5-9725-41cd-b373-84411b0f7e0d-1,[{'hyp1_paraphrases': ['Rita was pleased a sto...
113,test,2940,Matt tried to make pork fried rice.,Matt decided to put mayonnaise on some pasta.,2,Matt was hungry.,He decided to never experiment with pasta ever...,test,a175e648-e8f3-433d-90ec-194f916200fd-1,[{'hyp1_paraphrases': ['Matt decided to put ma...
114,test,1288,Jenny went to see her mother.,Jenny went to see her doctor.,2,Jenny was pregnant with her first child.,The doctor told her she was pregnant with twins.,test,e8c49cd0-0d28-4146-a781-7846f769470c-1,[{'hyp1_paraphrases': ['Jenny scheduled an app...

In [4]:
mturk_abductive_data.to_csv('paraphrased_pilot.csv', index=False)